# Generated by Django 4.2.6 on 2024-01-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'admin'), ('2', 'personnel'), ('3', 'etudiant')], default='1', max_length=10),
        ),
    ]
