# Generated by Django 4.2.6 on 2024-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='fin',
            field=models.DateField(),
        ),
    ]
