# Generated by Django 4.2.6 on 2024-01-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0008_alter_session_debut_alter_session_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='profie_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecole.session'),
        ),
    ]
