# Generated by Django 4.2.6 on 2024-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0009_etudiant_profie_pic_etudiant_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='profie_pic',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
