# Generated by Django 4.2.6 on 2024-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0010_remove_etudiant_profie_pic_etudiant_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='profile_pic',
            field=models.ImageField(default='media/photo1_1.jpg', upload_to='media/'),
        ),
    ]
