# Generated by Django 4.2.6 on 2024-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0011_alter_etudiant_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='numero_matricule',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
