# Generated by Django 4.2.6 on 2024-01-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0012_etudiant_numero_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='numero_matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
